----EMPLOYEE SALARIES	
SELECT EMPLOYEES.EMP_NO,
		EMPLOYEES.LAST_NAME,
		EMPLOYEES.FIRST_NAME,
		EMPLOYEES.SEX,
		SALARIES.SALARY
FROM EMPLOYEES
	LEFT JOIN SALARIES
	ON (EMPLOYEES.EMP_NO = SALARIES.EMP_NO)
ORDER BY EMPLOYEES.EMP_NO;	
		
--EMPLOYEES HIRED IN '86
SELECT FIRST_NAME, LAST_NAME, HIRE_DATE
FROM EMPLOYEES
WHERE HIRE_DATE BETWEEN '1986-01-01' AND '1986,12-31'
;


---MANAGER OF EACH DEPT
SELECT DEPT_MANAGER.DEPT_NO,
		DEPARTMENTS.DEPT_NAME,
		DEPT_MANAGER.EMP_NO,
		EMPLOYEES.LAST_NAME, 
		EMPLOYEES.FIRST_NAME
FROM DEPT_MANAGER
	INNER JOIN DEPARTMENTS
		ON(DEPT_MANAGER.DEPT_NO = DEPARTMENTS.DEPT_NO)
	INNER JOIN EMPLOYEES
		ON (DEPT_MANAGER.EMP_NO = EMPLOYEES.EMP_NO)
;		

---DEPT OF EACH EMP
SELECT EMPLOYEES.EMP_NO,
		EMPLOYEES.LAST_NAME,
		EMPLOYEES.FIRST_NAME,
		DEPARTMENTS.DEPT_NAME
FROM EMPLOYEES
	INNER JOIN DEPT_EMP
		ON (EMPLOYEES.EMP_NO = DEPT_EMP.EMP_NO)
	INNER JOIN DEPARTMENTS
		ON (DEPT_EMP.DEPT_NO = DEPARTMENTS.DEPT_NO)
ORDER BY EMPLOYEES.EMP_NO
;
---FIRST_NAME "HERCULES" AND LAST_NAME STARTS WITH "B"
SELECT FIRST_NAME, LAST_NAME, BIRTH_DATE, SEX
FROM EMPLOYEES
WHERE FIRST_NAME = 'HERCULES'
AND LAST_NAME LIKE 'B%'
;

----EMP IN SALES DEPT
SELECT EMPLOYEES.EMP_NO,
		EMPLOYEES.LAST_NAME,
		EMPLOYEES.FIRST_NAME,
		DEPARTMENTS.DEPT_NAME
FROM EMPLOYEES
	INNER JOIN DEPT_EMP
		ON (EMPLOYEES.EMP_NO = DEPT_EMP.EMP_NO)
	INNER JOIN DEPARTMENTS 
		ON (DEPT_EMP.DEPT_NO = DEPARTMENTS.DEPT_NO)
WHERE DEPARTMENTS.DEPT_NAME = 'SALES'
ORDER BY EMPLOYEES.EMP_NO
;


---EMP IN SALES & DEV DEPT
SELECT EMPLOYEES.EMP_NO,
		EMPLOYEES.LAST_NAME,
		EMPLOYEES.FIRST_NAME,
		DEPARTMENTS.DEPT_NAME
FROM EMPLOYEES
	INNER JOIN DEPT_EMP
		ON (EMPLOYEES.EMP_NO = DEPT_EMP.EMP_NO)
	INNER JOIN DEPARTMENTS
		ON (DEPT_EMP.DEPT_NO = DEPARTMENTS.DEPT_NO)
WHERE DEPARTMENTS.DEPT_NAME IN ('SALES', 'DEVELOPMENT')
ORDER BY EMPLOYEES.EMP_NO

;
---FREQUENCY COUNT (DESCENDING), EMP WITH SAME LAST NAME

SELECT LAST_NAME, COUNT(LAST_NAME)
FROM EMPLOYEES
GROUP BY LAST_NAME
ORDER BY COUNT(LAST_NAME) DESC
;