
CREATE TABLE TITLE (
	TITLE_ID varchar (30) PRIMARY KEY NOT NULL,
	TITLE Varchar (30) not null)
;	
CREATE TABLE EMPLOYEES (
	EMP_NO INT PRIMARY KEY NOT NULL,
	EMP_TITLE_ID VARCHAR (30) NOT NULL,
	BIRTH_DATE DATE NOT NULL,
	FIRST_NAME VARCHAR (30) NOT NULL,
	LAST_NAME VARCHAR (30) NOT NULL,
	SEX VARCHAR (30) NOT NULL,
	HIRE_DATE DATE NOT NULL,
	FOREIGN KEY(EMP_TITLE_ID) REFERENCES TITLE(TITLE_ID)
);	
CREATE TABLE DEPARTMENTS (
	DEPT_NO VARCHAR (30) PRIMARY KEY NOT NULL, 
	DEPT_NAME VARCHAR (30) NOT NULL)
;
CREATE TABLE DEPT_MANAGER (
	DEPT_NO VARCHAR (30) NOT NULL,
	EMP_NO INT NOT NULL, 
	FOREIGN KEY(EMP_NO) REFERENCES EMPLOYEES(EMP_NO),
	FOREIGN KEY(DEPT_NO) REFERENCES DEPARTMENTS(DEPT_NO),
	PRIMARY KEY (DEPT_NO, EMP_NO)
);	
CREATE TABLE DEPT_EMP (
	EMP_NO INT NOT NULL,
	FOREIGN KEY(EMP_NO) REFERENCES EMPLOYEES(EMP_NO),
	DEPT_NO VARCHAR (30) NOT NULL,
	FOREIGN KEY(DEPT_NO) REFERENCES DEPARTMENTS(DEPT_NO),
	PRIMARY KEY (EMP_NO, DEPT_NO))
;	
CREATE TABLE SALARIES (
	EMP_NO INT NOT NULL, 
	FOREIGN KEY(EMP_NO) REFERENCES EMPLOYEES(EMP_NO),
	SALARY INT NOT NULL,
	PRIMARY KEY (EMP_NO))
;	